spring:
  datasource:
    url: jdbc:mysql:///blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 1402285087
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
logging:
  level:
    root: warn
    com.hwd: info
  file: log/blog-pro.log

server:
  port: 8080